//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinance.Web.Resources.Common {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources_pt {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources_pt() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalFinance.Web.Resources.Common.CommonResources.pt", typeof(CommonResources_pt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Orçamentos.
        /// </summary>
        public static string Budgets {
            get {
                return ResourceManager.GetString("Budgets", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aplicativo de finanças.
        /// </summary>
        public static string FinanceAppAlt {
            get {
                return ResourceManager.GetString("FinanceAppAlt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Minimizar Menu.
        /// </summary>
        public static string MinimizeMenu {
            get {
                return ResourceManager.GetString("MinimizeMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Visão Geral.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Potes.
        /// </summary>
        public static string Pots {
            get {
                return ResourceManager.GetString("Pots", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contas Recorrentes.
        /// </summary>
        public static string RecurringBills {
            get {
                return ResourceManager.GetString("RecurringBills", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Transações.
        /// </summary>
        public static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
    }
}
