//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinance.Web.Resources.Login {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LoginResources_pt {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginResources_pt() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalFinance.Web.Resources.Login.LoginResources.pt", typeof(LoginResources_pt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já tem uma conta?.
        /// </summary>
        public static string AlreadyHaveAccount {
            get {
                return ResourceManager.GetString("AlreadyHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar Senha.
        /// </summary>
        public static string CreatePassword {
            get {
                return ResourceManager.GetString("CreatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrando....
        /// </summary>
        public static string LoggingIn {
            get {
                return ResourceManager.GetString("LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precisa criar uma conta?.
        /// </summary>
        public static string NeedAccount {
            get {
                return ResourceManager.GetString("NeedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve ter pelo menos 8 caracteres.
        /// </summary>
        public static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O aplicativo de finanças pessoais coloca você no controle dos seus gastos. Acompanhe transações, defina orçamentos e adicione a potes de economia com facilidade..
        /// </summary>
        public static string SidebarSubtitle {
            get {
                return ResourceManager.GetString("SidebarSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acompanhe seu dinheiro e economize para o seu futuro.
        /// </summary>
        public static string SidebarTitle {
            get {
                return ResourceManager.GetString("SidebarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastre-se.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro desconhecido. Tente novamente mais tarde..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Email e senha são obrigatórios..
        /// </summary>
        public static string EmailAndPasswordRequiredError {
            get {
                return ResourceManager.GetString("EmailAndPasswordRequiredError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Todos os campos são obrigatórios..
        /// </summary>
        public static string AllFieldsRequiredError {
            get {
                return ResourceManager.GetString("AllFieldsRequiredError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Esqueci minha senha.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Informe seu email e enviaremos um código para redefinir sua senha..
        /// </summary>
        public static string ForgotPasswordInstructions {
            get {
                return ResourceManager.GetString("ForgotPasswordInstructions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enviar código.
        /// </summary>
        public static string SendCode {
            get {
                return ResourceManager.GetString("SendCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enviando código....
        /// </summary>
        public static string SendingCode {
            get {
                return ResourceManager.GetString("SendingCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Voltar para o login.
        /// </summary>
        public static string BackToLogin {
            get {
                return ResourceManager.GetString("BackToLogin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Se este email estiver cadastrado, você receberá um código em instantes..
        /// </summary>
        public static string CodeSentSuccess {
            get {
                return ResourceManager.GetString("CodeSentSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email é obrigatório..
        /// </summary>
        public static string EmailRequiredError {
            get {
                return ResourceManager.GetString("EmailRequiredError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Código de verificação.
        /// </summary>
        public static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insira o código recebido por email para redefinição da sua senha..
        /// </summary>
        public static string VerificationCodeInstructions {
            get {
                return ResourceManager.GetString("VerificationCodeInstructions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirmar código.
        /// </summary>
        public static string ConfirmCode {
            get {
                return ResourceManager.GetString("ConfirmCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Verificando....
        /// </summary>
        public static string ConfirmingCode {
            get {
                return ResourceManager.GetString("ConfirmingCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O código é obrigatório..
        /// </summary>
        public static string CodeRequiredError {
            get {
                return ResourceManager.GetString("CodeRequiredError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nova senha.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insira uma nova senha e confirme..
        /// </summary>
        public static string NewPasswordInstructions {
            get {
                return ResourceManager.GetString("NewPasswordInstructions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirmar nova senha.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Atualizando....
        /// </summary>
        public static string UpdatingPassword {
            get {
                return ResourceManager.GetString("UpdatingPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to As senhas não estão iguais..
        /// </summary>
        public static string PasswordsDoNotMatchError {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatchError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Senha alterada com sucesso..
        /// </summary>
        public static string PasswordChangedSuccess {
            get {
                return ResourceManager.GetString("PasswordChangedSuccess", resourceCulture);
            }
        }

    }
}
