//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinance.Web.Resources.Login {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LoginResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalFinance.Web.Resources.Login.LoginResources", typeof(LoginResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string AlreadyHaveAccount {
            get {
                return ResourceManager.GetString("AlreadyHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Password.
        /// </summary>
        public static string CreatePassword {
            get {
                return ResourceManager.GetString("CreatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in....
        /// </summary>
        public static string LoggingIn {
            get {
                return ResourceManager.GetString("LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to create an account?.
        /// </summary>
        public static string NeedAccount {
            get {
                return ResourceManager.GetString("NeedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must be at least 8 characters.
        /// </summary>
        public static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal finance app puts you in control of your spending. Track transactions, set budgets, and add to savings pots easily..
        /// </summary>
        public static string SidebarSubtitle {
            get {
                return ResourceManager.GetString("SidebarSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep track of your money and save for your future.
        /// </summary>
        public static string SidebarTitle {
            get {
                return ResourceManager.GetString("SidebarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred. Please try again later..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Email and password are required..
        /// </summary>
        public static string EmailAndPasswordRequiredError {
            get {
                return ResourceManager.GetString("EmailAndPasswordRequiredError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All fields are required..
        /// </summary>
        public static string AllFieldsRequiredError {
            get {
                return ResourceManager.GetString("AllFieldsRequiredError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter your email and we will send you a code to reset your password..
        /// </summary>
        public static string ForgotPasswordInstructions {
            get {
                return ResourceManager.GetString("ForgotPasswordInstructions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Send code.
        /// </summary>
        public static string SendCode {
            get {
                return ResourceManager.GetString("SendCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sending code....
        /// </summary>
        public static string SendingCode {
            get {
                return ResourceManager.GetString("SendingCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Back to login.
        /// </summary>
        public static string BackToLogin {
            get {
                return ResourceManager.GetString("BackToLogin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to If this email is registered, you will receive a code shortly..
        /// </summary>
        public static string CodeSentSuccess {
            get {
                return ResourceManager.GetString("CodeSentSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string EmailRequiredError {
            get {
                return ResourceManager.GetString("EmailRequiredError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Verification code.
        /// </summary>
        public static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter the code you received by email to reset your password..
        /// </summary>
        public static string VerificationCodeInstructions {
            get {
                return ResourceManager.GetString("VerificationCodeInstructions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm code.
        /// </summary>
        public static string ConfirmCode {
            get {
                return ResourceManager.GetString("ConfirmCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirming....
        /// </summary>
        public static string ConfirmingCode {
            get {
                return ResourceManager.GetString("ConfirmingCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Code is required..
        /// </summary>
        public static string CodeRequiredError {
            get {
                return ResourceManager.GetString("CodeRequiredError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter a new password and confirm it..
        /// </summary>
        public static string NewPasswordInstructions {
            get {
                return ResourceManager.GetString("NewPasswordInstructions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Updating....
        /// </summary>
        public static string UpdatingPassword {
            get {
                return ResourceManager.GetString("UpdatingPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string PasswordsDoNotMatchError {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatchError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully..
        /// </summary>
        public static string PasswordChangedSuccess {
            get {
                return ResourceManager.GetString("PasswordChangedSuccess", resourceCulture);
            }
        }

    }
}
