//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinance.Web.Resources.Bills {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BillsResources_pt {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BillsResources_pt() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalFinance.Web.Resources.Bills.BillsResources.pt", typeof(BillsResources_pt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to + Adicionar Nova Conta Recorrente.
        /// </summary>
        public static string AddBillCta {
            get {
                return ResourceManager.GetString("AddBillCta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nenhuma conta registrada..
        /// </summary>
        public static string NoBillRecorded {
            get {
                return ResourceManager.GetString("NoBillRecorded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total de Contas.
        /// </summary>
        public static string TotalBillsLabel {
            get {
                return ResourceManager.GetString("TotalBillsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resumo.
        /// </summary>
        public static string SummaryTitle {
            get {
                return ResourceManager.GetString("SummaryTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contas Pagas.
        /// </summary>
        public static string PaidBillsLabel {
            get {
                return ResourceManager.GetString("PaidBillsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total a Vencer.
        /// </summary>
        public static string TotalUpcomingLabel {
            get {
                return ResourceManager.GetString("TotalUpcomingLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vencendo em Breve.
        /// </summary>
        public static string DueSoonLabel {
            get {
                return ResourceManager.GetString("DueSoonLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Buscar contas.
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ordenar por.
        /// </summary>
        public static string SortByLabel {
            get {
                return ResourceManager.GetString("SortByLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Título da Conta.
        /// </summary>
        public static string BillTitleColumn {
            get {
                return ResourceManager.GetString("BillTitleColumn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data de Vencimento.
        /// </summary>
        public static string DueDateColumn {
            get {
                return ResourceManager.GetString("DueDateColumn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string AmountColumn {
            get {
                return ResourceManager.GetString("AmountColumn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mensal - dia {0}.
        /// </summary>
        public static string MonthlyDueDateFormat {
            get {
                return ResourceManager.GetString("MonthlyDueDateFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mais Recente.
        /// </summary>
        public static string Latest {
            get {
                return ResourceManager.GetString("Latest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mais Antigo.
        /// </summary>
        public static string Oldest {
            get {
                return ResourceManager.GetString("Oldest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A a Z.
        /// </summary>
        public static string AToZ {
            get {
                return ResourceManager.GetString("AToZ", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Z a A.
        /// </summary>
        public static string ZToA {
            get {
                return ResourceManager.GetString("ZToA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maior Valor.
        /// </summary>
        public static string Highest {
            get {
                return ResourceManager.GetString("Highest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Menor Valor.
        /// </summary>
        public static string Lowest {
            get {
                return ResourceManager.GetString("Lowest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adicionar Nova Conta Recorrente.
        /// </summary>
        public static string AddBillTitle {
            get {
                return ResourceManager.GetString("AddBillTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adicione uma nova conta recorrente para acompanhar seus pagamentos regulares..
        /// </summary>
        public static string AddBillSubtitle {
            get {
                return ResourceManager.GetString("AddBillSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Destinatário.
        /// </summary>
        public static string ParticipantLabel {
            get {
                return ResourceManager.GetString("ParticipantLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Selecione o Destinatário.
        /// </summary>
        public static string ParticipantPlaceholder {
            get {
                return ResourceManager.GetString("ParticipantPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nenhum destinatário registrado.
        /// </summary>
        public static string NoParticipantsRegisteredPlaceholder {
            get {
                return ResourceManager.GetString("NoParticipantsRegisteredPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string CategoryLabel {
            get {
                return ResourceManager.GetString("CategoryLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Selecione a Categoria.
        /// </summary>
        public static string CategoryPlaceholder {
            get {
                return ResourceManager.GetString("CategoryPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nenhuma categoria registrada.
        /// </summary>
        public static string NoCategoriesRegisteredPlaceholder {
            get {
                return ResourceManager.GetString("NoCategoriesRegisteredPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string AmountLabel {
            get {
                return ResourceManager.GetString("AmountLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ex. 50.
        /// </summary>
        public static string AmountPlaceholder {
            get {
                return ResourceManager.GetString("AmountPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data de Vencimento.
        /// </summary>
        public static string DueDateLabel {
            get {
                return ResourceManager.GetString("DueDateLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total de Parcelas.
        /// </summary>
        public static string InstallmentsTotalLabel {
            get {
                return ResourceManager.GetString("InstallmentsTotalLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ex. 12.
        /// </summary>
        public static string InstallmentsTotalPlaceholder {
            get {
                return ResourceManager.GetString("InstallmentsTotalPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parcelas Pagas.
        /// </summary>
        public static string InstallmentsPaidLabel {
            get {
                return ResourceManager.GetString("InstallmentsPaidLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ex. 0.
        /// </summary>
        public static string InstallmentsPaidPlaceholder {
            get {
                return ResourceManager.GetString("InstallmentsPaidPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adicionar Conta.
        /// </summary>
        public static string AddBillButton {
            get {
                return ResourceManager.GetString("AddBillButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Por favor, preencha todos os campos obrigatórios..
        /// </summary>
        public static string RequiredFieldsError {
            get {
                return ResourceManager.GetString("RequiredFieldsError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Algo deu errado. Tente novamente..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Conta adicionada com sucesso.
        /// </summary>
        public static string BillRegisteredSuccessMessage {
            get {
                return ResourceManager.GetString("BillRegisteredSuccessMessage", resourceCulture);
            }
        }
    }
}
