//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinance.Web.Resources.Bills {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BillsResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BillsResources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalFinance.Web.Resources.Bills.BillsResources", typeof(BillsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to + Add New Recurring Bill.
        /// </summary>
        public static string AddBillCta {
            get {
                return ResourceManager.GetString("AddBillCta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No bill recorded..
        /// </summary>
        public static string NoBillRecorded {
            get {
                return ResourceManager.GetString("NoBillRecorded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total Bills.
        /// </summary>
        public static string TotalBillsLabel {
            get {
                return ResourceManager.GetString("TotalBillsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string SummaryTitle {
            get {
                return ResourceManager.GetString("SummaryTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Paid Bills.
        /// </summary>
        public static string PaidBillsLabel {
            get {
                return ResourceManager.GetString("PaidBillsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total Upcoming.
        /// </summary>
        public static string TotalUpcomingLabel {
            get {
                return ResourceManager.GetString("TotalUpcomingLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Due Soon.
        /// </summary>
        public static string DueSoonLabel {
            get {
                return ResourceManager.GetString("DueSoonLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search bills.
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        public static string SortByLabel {
            get {
                return ResourceManager.GetString("SortByLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bill Title.
        /// </summary>
        public static string BillTitleColumn {
            get {
                return ResourceManager.GetString("BillTitleColumn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string DueDateColumn {
            get {
                return ResourceManager.GetString("DueDateColumn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string AmountColumn {
            get {
                return ResourceManager.GetString("AmountColumn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Monthly - {0}.
        /// </summary>
        public static string MonthlyDueDateFormat {
            get {
                return ResourceManager.GetString("MonthlyDueDateFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        public static string Latest {
            get {
                return ResourceManager.GetString("Latest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Oldest.
        /// </summary>
        public static string Oldest {
            get {
                return ResourceManager.GetString("Oldest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A to Z.
        /// </summary>
        public static string AToZ {
            get {
                return ResourceManager.GetString("AToZ", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Z to A.
        /// </summary>
        public static string ZToA {
            get {
                return ResourceManager.GetString("ZToA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Highest.
        /// </summary>
        public static string Highest {
            get {
                return ResourceManager.GetString("Highest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lowest.
        /// </summary>
        public static string Lowest {
            get {
                return ResourceManager.GetString("Lowest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add New Recurring Bill.
        /// </summary>
        public static string AddBillTitle {
            get {
                return ResourceManager.GetString("AddBillTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add a new recurring bill to keep track of your regular payments..
        /// </summary>
        public static string AddBillSubtitle {
            get {
                return ResourceManager.GetString("AddBillSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Recipient.
        /// </summary>
        public static string ParticipantLabel {
            get {
                return ResourceManager.GetString("ParticipantLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select Recipient.
        /// </summary>
        public static string ParticipantPlaceholder {
            get {
                return ResourceManager.GetString("ParticipantPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No recipients registered.
        /// </summary>
        public static string NoParticipantsRegisteredPlaceholder {
            get {
                return ResourceManager.GetString("NoParticipantsRegisteredPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CategoryLabel {
            get {
                return ResourceManager.GetString("CategoryLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select Category.
        /// </summary>
        public static string CategoryPlaceholder {
            get {
                return ResourceManager.GetString("CategoryPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No categories registered.
        /// </summary>
        public static string NoCategoriesRegisteredPlaceholder {
            get {
                return ResourceManager.GetString("NoCategoriesRegisteredPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string AmountLabel {
            get {
                return ResourceManager.GetString("AmountLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. 50.
        /// </summary>
        public static string AmountPlaceholder {
            get {
                return ResourceManager.GetString("AmountPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string DueDateLabel {
            get {
                return ResourceManager.GetString("DueDateLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total Installments.
        /// </summary>
        public static string InstallmentsTotalLabel {
            get {
                return ResourceManager.GetString("InstallmentsTotalLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. 12.
        /// </summary>
        public static string InstallmentsTotalPlaceholder {
            get {
                return ResourceManager.GetString("InstallmentsTotalPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installments Paid.
        /// </summary>
        public static string InstallmentsPaidLabel {
            get {
                return ResourceManager.GetString("InstallmentsPaidLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. 0.
        /// </summary>
        public static string InstallmentsPaidPlaceholder {
            get {
                return ResourceManager.GetString("InstallmentsPaidPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Bill.
        /// </summary>
        public static string AddBillButton {
            get {
                return ResourceManager.GetString("AddBillButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please fill in all required fields..
        /// </summary>
        public static string RequiredFieldsError {
            get {
                return ResourceManager.GetString("RequiredFieldsError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bill added successfully.
        /// </summary>
        public static string BillRegisteredSuccessMessage {
            get {
                return ResourceManager.GetString("BillRegisteredSuccessMessage", resourceCulture);
            }
        }
    }
}
