//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinance.Web.Resources.Profile {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProfileResources_pt {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProfileResources_pt() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalFinance.Web.Resources.Profile.ProfileResources.pt", typeof(ProfileResources_pt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Meu Perfil.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Informações do Perfil.
        /// </summary>
        public static string ProfileInfoTitle {
            get {
                return ResourceManager.GetString("ProfileInfoTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ex. João Silva.
        /// </summary>
        public static string NamePlaceholder {
            get {
                return ResourceManager.GetString("NamePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ex. joao@exemplo.com.
        /// </summary>
        public static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to URL da Foto de Perfil.
        /// </summary>
        public static string ProfileImageLabel {
            get {
                return ResourceManager.GetString("ProfileImageLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://....
        /// </summary>
        public static string ProfileImagePlaceholder {
            get {
                return ResourceManager.GetString("ProfileImagePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Receber notificações por email.
        /// </summary>
        public static string ReceiveEmailNotificationsLabel {
            get {
                return ResourceManager.GetString("ReceiveEmailNotificationsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Salvar Alterações.
        /// </summary>
        public static string SaveChangesButton {
            get {
                return ResourceManager.GetString("SaveChangesButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Perfil atualizado com sucesso.
        /// </summary>
        public static string ProfileUpdatedSuccessMessage {
            get {
                return ResourceManager.GetString("ProfileUpdatedSuccessMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alterar Senha.
        /// </summary>
        public static string ChangePasswordTitle {
            get {
                return ResourceManager.GetString("ChangePasswordTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Senha Atual.
        /// </summary>
        public static string CurrentPasswordLabel {
            get {
                return ResourceManager.GetString("CurrentPasswordLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nova Senha.
        /// </summary>
        public static string NewPasswordLabel {
            get {
                return ResourceManager.GetString("NewPasswordLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alterar Senha.
        /// </summary>
        public static string ChangePasswordButton {
            get {
                return ResourceManager.GetString("ChangePasswordButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Senha atualizada com sucesso.
        /// </summary>
        public static string PasswordUpdatedSuccessMessage {
            get {
                return ResourceManager.GetString("PasswordUpdatedSuccessMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Zona de Perigo.
        /// </summary>
        public static string DangerZoneTitle {
            get {
                return ResourceManager.GetString("DangerZoneTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Depois de excluir sua conta, não há como voltar atrás. Todos os seus dados serão removidos permanentemente..
        /// </summary>
        public static string DeleteAccountDescription {
            get {
                return ResourceManager.GetString("DeleteAccountDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Excluir Minha Conta.
        /// </summary>
        public static string DeleteAccountCta {
            get {
                return ResourceManager.GetString("DeleteAccountCta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Excluir sua conta?.
        /// </summary>
        public static string DeleteAccountTitle {
            get {
                return ResourceManager.GetString("DeleteAccountTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tem certeza de que deseja excluir sua conta? Esta ação não pode ser desfeita, e todos os seus dados serão removidos para sempre..
        /// </summary>
        public static string DeleteAccountMessage {
            get {
                return ResourceManager.GetString("DeleteAccountMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sim, Excluir Minha Conta.
        /// </summary>
        public static string ConfirmDeletionButton {
            get {
                return ResourceManager.GetString("ConfirmDeletionButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Não, Voltar.
        /// </summary>
        public static string GoBackButton {
            get {
                return ResourceManager.GetString("GoBackButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Por favor, preencha todos os campos obrigatórios..
        /// </summary>
        public static string RequiredFieldsError {
            get {
                return ResourceManager.GetString("RequiredFieldsError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Algo deu errado. Tente novamente..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Conta excluída com sucesso.
        /// </summary>
        public static string AccountDeletedSuccessMessage {
            get {
                return ResourceManager.GetString("AccountDeletedSuccessMessage", resourceCulture);
            }
        }
    }
}
