//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinance.Web.Resources.Pots {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PotsResources_pt {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PotsResources_pt() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalFinance.Web.Resources.Pots.PotsResources.pt", typeof(PotsResources_pt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to + Adicionar Novo Pote.
        /// </summary>
        public static string AddPotCta {
            get {
                return ResourceManager.GetString("AddPotCta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adicionar Novo Pote.
        /// </summary>
        public static string AddPotTitle {
            get {
                return ResourceManager.GetString("AddPotTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Crie um pote para definir metas de economia. Isso pode ajudar você a se manter no caminho certo enquanto economiza para compras especiais..
        /// </summary>
        public static string AddPotSubtitle {
            get {
                return ResourceManager.GetString("AddPotSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nome do Pote.
        /// </summary>
        public static string PotNameLabel {
            get {
                return ResourceManager.GetString("PotNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ex. Dias de Chuva.
        /// </summary>
        public static string PotNamePlaceholder {
            get {
                return ResourceManager.GetString("PotNamePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} caracteres restantes.
        /// </summary>
        public static string CharactersLeftFormat {
            get {
                return ResourceManager.GetString("CharactersLeftFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Meta.
        /// </summary>
        public static string TargetLabel {
            get {
                return ResourceManager.GetString("TargetLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ex. 2000.
        /// </summary>
        public static string TargetPlaceholder {
            get {
                return ResourceManager.GetString("TargetPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        public static string ThemeLabel {
            get {
                return ResourceManager.GetString("ThemeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Selecione o Tema.
        /// </summary>
        public static string ThemePlaceholder {
            get {
                return ResourceManager.GetString("ThemePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Já utilizado.
        /// </summary>
        public static string AlreadyUsedBadge {
            get {
                return ResourceManager.GetString("AlreadyUsedBadge", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adicionar Pote.
        /// </summary>
        public static string AddPotButton {
            get {
                return ResourceManager.GetString("AddPotButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nova Cor de Tema.
        /// </summary>
        public static string AddNewThemeTitle {
            get {
                return ResourceManager.GetString("AddNewThemeTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nome da Cor.
        /// </summary>
        public static string CustomColorNameLabel {
            get {
                return ResourceManager.GetString("CustomColorNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ex. Azul Céu.
        /// </summary>
        public static string CustomColorNamePlaceholder {
            get {
                return ResourceManager.GetString("CustomColorNamePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cor.
        /// </summary>
        public static string CustomColorValueLabel {
            get {
                return ResourceManager.GetString("CustomColorValueLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adicionar Tema.
        /// </summary>
        public static string AddThemeButton {
            get {
                return ResourceManager.GetString("AddThemeButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Por favor, preencha todos os campos obrigatórios..
        /// </summary>
        public static string RequiredFieldsError {
            get {
                return ResourceManager.GetString("RequiredFieldsError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Algo deu errado. Tente novamente..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nenhum pote registrado..
        /// </summary>
        public static string NoPotRecorded {
            get {
                return ResourceManager.GetString("NoPotRecorded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total Economizado.
        /// </summary>
        public static string TotalSavedLabel {
            get {
                return ResourceManager.GetString("TotalSavedLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Meta de {0}.
        /// </summary>
        public static string TargetOfFormat {
            get {
                return ResourceManager.GetString("TargetOfFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to + Adicionar Dinheiro.
        /// </summary>
        public static string AddMoneyCta {
            get {
                return ResourceManager.GetString("AddMoneyCta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retirar.
        /// </summary>
        public static string WithdrawCta {
            get {
                return ResourceManager.GetString("WithdrawCta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Opções do pote.
        /// </summary>
        public static string PotOptionsAriaLabel {
            get {
                return ResourceManager.GetString("PotOptionsAriaLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Editar Pote.
        /// </summary>
        public static string EditPotCta {
            get {
                return ResourceManager.GetString("EditPotCta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Excluir Pote.
        /// </summary>
        public static string DeletePotCta {
            get {
                return ResourceManager.GetString("DeletePotCta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Editar Pote.
        /// </summary>
        public static string EditPotTitle {
            get {
                return ResourceManager.GetString("EditPotTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Se suas metas de economia mudarem, sinta-se à vontade para atualizar seus potes..
        /// </summary>
        public static string EditPotSubtitle {
            get {
                return ResourceManager.GetString("EditPotSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Salvar Alterações.
        /// </summary>
        public static string SaveChangesButton {
            get {
                return ResourceManager.GetString("SaveChangesButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Excluir '{0}'?.
        /// </summary>
        public static string DeletePotTitleFormat {
            get {
                return ResourceManager.GetString("DeletePotTitleFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tem certeza de que deseja excluir este pote? Esta ação não pode ser desfeita, e todos os dados dentro dele serão removidos para sempre..
        /// </summary>
        public static string DeletePotMessage {
            get {
                return ResourceManager.GetString("DeletePotMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sim, Confirmar Exclusão.
        /// </summary>
        public static string ConfirmDeletionButton {
            get {
                return ResourceManager.GetString("ConfirmDeletionButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Não, Voltar.
        /// </summary>
        public static string GoBackButton {
            get {
                return ResourceManager.GetString("GoBackButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pote adicionado com sucesso.
        /// </summary>
        public static string PotRegisteredSuccessMessage {
            get {
                return ResourceManager.GetString("PotRegisteredSuccessMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pote atualizado com sucesso.
        /// </summary>
        public static string PotUpdatedSuccessMessage {
            get {
                return ResourceManager.GetString("PotUpdatedSuccessMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pote excluído com sucesso.
        /// </summary>
        public static string PotDeletedSuccessMessage {
            get {
                return ResourceManager.GetString("PotDeletedSuccessMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Verde.
        /// </summary>
        public static string ColorGreen {
            get {
                return ResourceManager.GetString("ColorGreen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Amarelo.
        /// </summary>
        public static string ColorYellow {
            get {
                return ResourceManager.GetString("ColorYellow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ciano.
        /// </summary>
        public static string ColorCyan {
            get {
                return ResourceManager.GetString("ColorCyan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Azul Marinho.
        /// </summary>
        public static string ColorNavy {
            get {
                return ResourceManager.GetString("ColorNavy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vermelho.
        /// </summary>
        public static string ColorRed {
            get {
                return ResourceManager.GetString("ColorRed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Roxo.
        /// </summary>
        public static string ColorPurple {
            get {
                return ResourceManager.GetString("ColorPurple", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Roxo Claro.
        /// </summary>
        public static string ColorPurpleLight {
            get {
                return ResourceManager.GetString("ColorPurpleLight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Turquesa.
        /// </summary>
        public static string ColorTurquoise {
            get {
                return ResourceManager.GetString("ColorTurquoise", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Marrom.
        /// </summary>
        public static string ColorBrown {
            get {
                return ResourceManager.GetString("ColorBrown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Magenta.
        /// </summary>
        public static string ColorMagenta {
            get {
                return ResourceManager.GetString("ColorMagenta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Azul.
        /// </summary>
        public static string ColorBlue {
            get {
                return ResourceManager.GetString("ColorBlue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cinza Azulado.
        /// </summary>
        public static string ColorNavyGrey {
            get {
                return ResourceManager.GetString("ColorNavyGrey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Verde Militar.
        /// </summary>
        public static string ColorArmyGreen {
            get {
                return ResourceManager.GetString("ColorArmyGreen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dourado.
        /// </summary>
        public static string ColorGold {
            get {
                return ResourceManager.GetString("ColorGold", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Laranja.
        /// </summary>
        public static string ColorOrange {
            get {
                return ResourceManager.GetString("ColorOrange", resourceCulture);
            }
        }
    }
}
