//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinance.Web.Resources.Pots {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PotsResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PotsResources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalFinance.Web.Resources.Pots.PotsResources", typeof(PotsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to + Add New Pot.
        /// </summary>
        public static string AddPotCta {
            get {
                return ResourceManager.GetString("AddPotCta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add New Pot.
        /// </summary>
        public static string AddPotTitle {
            get {
                return ResourceManager.GetString("AddPotTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create a pot to set savings targets. These can help keep you on track as you save for special purchases..
        /// </summary>
        public static string AddPotSubtitle {
            get {
                return ResourceManager.GetString("AddPotSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pot Name.
        /// </summary>
        public static string PotNameLabel {
            get {
                return ResourceManager.GetString("PotNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. Rainy Days.
        /// </summary>
        public static string PotNamePlaceholder {
            get {
                return ResourceManager.GetString("PotNamePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} characters left.
        /// </summary>
        public static string CharactersLeftFormat {
            get {
                return ResourceManager.GetString("CharactersLeftFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string TargetLabel {
            get {
                return ResourceManager.GetString("TargetLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. 2000.
        /// </summary>
        public static string TargetPlaceholder {
            get {
                return ResourceManager.GetString("TargetPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string ThemeLabel {
            get {
                return ResourceManager.GetString("ThemeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select Theme.
        /// </summary>
        public static string ThemePlaceholder {
            get {
                return ResourceManager.GetString("ThemePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Already used.
        /// </summary>
        public static string AlreadyUsedBadge {
            get {
                return ResourceManager.GetString("AlreadyUsedBadge", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Pot.
        /// </summary>
        public static string AddPotButton {
            get {
                return ResourceManager.GetString("AddPotButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Theme Color.
        /// </summary>
        public static string AddNewThemeTitle {
            get {
                return ResourceManager.GetString("AddNewThemeTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Color Name.
        /// </summary>
        public static string CustomColorNameLabel {
            get {
                return ResourceManager.GetString("CustomColorNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. Sky Blue.
        /// </summary>
        public static string CustomColorNamePlaceholder {
            get {
                return ResourceManager.GetString("CustomColorNamePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string CustomColorValueLabel {
            get {
                return ResourceManager.GetString("CustomColorValueLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Theme.
        /// </summary>
        public static string AddThemeButton {
            get {
                return ResourceManager.GetString("AddThemeButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please fill in all required fields..
        /// </summary>
        public static string RequiredFieldsError {
            get {
                return ResourceManager.GetString("RequiredFieldsError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No pot recorded..
        /// </summary>
        public static string NoPotRecorded {
            get {
                return ResourceManager.GetString("NoPotRecorded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total Saved.
        /// </summary>
        public static string TotalSavedLabel {
            get {
                return ResourceManager.GetString("TotalSavedLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Target of {0}.
        /// </summary>
        public static string TargetOfFormat {
            get {
                return ResourceManager.GetString("TargetOfFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to + Add Money.
        /// </summary>
        public static string AddMoneyCta {
            get {
                return ResourceManager.GetString("AddMoneyCta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Withdraw.
        /// </summary>
        public static string WithdrawCta {
            get {
                return ResourceManager.GetString("WithdrawCta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pot options.
        /// </summary>
        public static string PotOptionsAriaLabel {
            get {
                return ResourceManager.GetString("PotOptionsAriaLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit Pot.
        /// </summary>
        public static string EditPotCta {
            get {
                return ResourceManager.GetString("EditPotCta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete Pot.
        /// </summary>
        public static string DeletePotCta {
            get {
                return ResourceManager.GetString("DeletePotCta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit Pot.
        /// </summary>
        public static string EditPotTitle {
            get {
                return ResourceManager.GetString("EditPotTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to If your saving targets change, feel free to update your pots..
        /// </summary>
        public static string EditPotSubtitle {
            get {
                return ResourceManager.GetString("EditPotSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string SaveChangesButton {
            get {
                return ResourceManager.GetString("SaveChangesButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete '{0}'?.
        /// </summary>
        public static string DeletePotTitleFormat {
            get {
                return ResourceManager.GetString("DeletePotTitleFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this pot? This action cannot be reversed, and all the data inside it will be removed forever..
        /// </summary>
        public static string DeletePotMessage {
            get {
                return ResourceManager.GetString("DeletePotMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes, Confirm Deletion.
        /// </summary>
        public static string ConfirmDeletionButton {
            get {
                return ResourceManager.GetString("ConfirmDeletionButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No, Go Back.
        /// </summary>
        public static string GoBackButton {
            get {
                return ResourceManager.GetString("GoBackButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pot added successfully.
        /// </summary>
        public static string PotRegisteredSuccessMessage {
            get {
                return ResourceManager.GetString("PotRegisteredSuccessMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pot updated successfully.
        /// </summary>
        public static string PotUpdatedSuccessMessage {
            get {
                return ResourceManager.GetString("PotUpdatedSuccessMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pot deleted successfully.
        /// </summary>
        public static string PotDeletedSuccessMessage {
            get {
                return ResourceManager.GetString("PotDeletedSuccessMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string ColorGreen {
            get {
                return ResourceManager.GetString("ColorGreen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string ColorYellow {
            get {
                return ResourceManager.GetString("ColorYellow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cyan.
        /// </summary>
        public static string ColorCyan {
            get {
                return ResourceManager.GetString("ColorCyan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Navy.
        /// </summary>
        public static string ColorNavy {
            get {
                return ResourceManager.GetString("ColorNavy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string ColorRed {
            get {
                return ResourceManager.GetString("ColorRed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string ColorPurple {
            get {
                return ResourceManager.GetString("ColorPurple", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Purple Light.
        /// </summary>
        public static string ColorPurpleLight {
            get {
                return ResourceManager.GetString("ColorPurpleLight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Turquoise.
        /// </summary>
        public static string ColorTurquoise {
            get {
                return ResourceManager.GetString("ColorTurquoise", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        public static string ColorBrown {
            get {
                return ResourceManager.GetString("ColorBrown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Magenta.
        /// </summary>
        public static string ColorMagenta {
            get {
                return ResourceManager.GetString("ColorMagenta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string ColorBlue {
            get {
                return ResourceManager.GetString("ColorBlue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Navy Grey.
        /// </summary>
        public static string ColorNavyGrey {
            get {
                return ResourceManager.GetString("ColorNavyGrey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Army Green.
        /// </summary>
        public static string ColorArmyGreen {
            get {
                return ResourceManager.GetString("ColorArmyGreen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        public static string ColorGold {
            get {
                return ResourceManager.GetString("ColorGold", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string ColorOrange {
            get {
                return ResourceManager.GetString("ColorOrange", resourceCulture);
            }
        }
    }
}
