//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinance.Web.Resources.Budgets {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BudgetsResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BudgetsResources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalFinance.Web.Resources.Budgets.BudgetsResources", typeof(BudgetsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to + Add New Budget.
        /// </summary>
        public static string AddBudgetCta {
            get {
                return ResourceManager.GetString("AddBudgetCta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add New Budget.
        /// </summary>
        public static string AddBudgetTitle {
            get {
                return ResourceManager.GetString("AddBudgetTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose a category to set a spending budget. These categories can help you monitor spending..
        /// </summary>
        public static string AddBudgetSubtitle {
            get {
                return ResourceManager.GetString("AddBudgetSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Budget Category.
        /// </summary>
        public static string BudgetCategoryLabel {
            get {
                return ResourceManager.GetString("BudgetCategoryLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select Category.
        /// </summary>
        public static string BudgetCategoryPlaceholder {
            get {
                return ResourceManager.GetString("BudgetCategoryPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximum Spend.
        /// </summary>
        public static string MaximumSpendLabel {
            get {
                return ResourceManager.GetString("MaximumSpendLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. 2000.
        /// </summary>
        public static string MaximumSpendPlaceholder {
            get {
                return ResourceManager.GetString("MaximumSpendPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string ThemeLabel {
            get {
                return ResourceManager.GetString("ThemeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select Theme.
        /// </summary>
        public static string ThemePlaceholder {
            get {
                return ResourceManager.GetString("ThemePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Already used.
        /// </summary>
        public static string AlreadyUsedBadge {
            get {
                return ResourceManager.GetString("AlreadyUsedBadge", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Budget.
        /// </summary>
        public static string AddBudgetButton {
            get {
                return ResourceManager.GetString("AddBudgetButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Theme Color.
        /// </summary>
        public static string AddNewThemeTitle {
            get {
                return ResourceManager.GetString("AddNewThemeTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Color Name.
        /// </summary>
        public static string CustomColorNameLabel {
            get {
                return ResourceManager.GetString("CustomColorNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. Sky Blue.
        /// </summary>
        public static string CustomColorNamePlaceholder {
            get {
                return ResourceManager.GetString("CustomColorNamePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string CustomColorValueLabel {
            get {
                return ResourceManager.GetString("CustomColorValueLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Theme.
        /// </summary>
        public static string AddThemeButton {
            get {
                return ResourceManager.GetString("AddThemeButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please fill in all required fields..
        /// </summary>
        public static string RequiredFieldsError {
            get {
                return ResourceManager.GetString("RequiredFieldsError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No budget recorded..
        /// </summary>
        public static string NoBudgetRecorded {
            get {
                return ResourceManager.GetString("NoBudgetRecorded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string ColorGreen {
            get {
                return ResourceManager.GetString("ColorGreen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string ColorYellow {
            get {
                return ResourceManager.GetString("ColorYellow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cyan.
        /// </summary>
        public static string ColorCyan {
            get {
                return ResourceManager.GetString("ColorCyan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Navy.
        /// </summary>
        public static string ColorNavy {
            get {
                return ResourceManager.GetString("ColorNavy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string ColorRed {
            get {
                return ResourceManager.GetString("ColorRed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string ColorPurple {
            get {
                return ResourceManager.GetString("ColorPurple", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Purple Light.
        /// </summary>
        public static string ColorPurpleLight {
            get {
                return ResourceManager.GetString("ColorPurpleLight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Turquoise.
        /// </summary>
        public static string ColorTurquoise {
            get {
                return ResourceManager.GetString("ColorTurquoise", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        public static string ColorBrown {
            get {
                return ResourceManager.GetString("ColorBrown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Magenta.
        /// </summary>
        public static string ColorMagenta {
            get {
                return ResourceManager.GetString("ColorMagenta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string ColorBlue {
            get {
                return ResourceManager.GetString("ColorBlue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Navy Grey.
        /// </summary>
        public static string ColorNavyGrey {
            get {
                return ResourceManager.GetString("ColorNavyGrey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Army Green.
        /// </summary>
        public static string ColorArmyGreen {
            get {
                return ResourceManager.GetString("ColorArmyGreen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        public static string ColorGold {
            get {
                return ResourceManager.GetString("ColorGold", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string ColorOrange {
            get {
                return ResourceManager.GetString("ColorOrange", resourceCulture);
            }
        }
    }
}
