//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinance.Web.Resources.Transactions {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TransactionsResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TransactionsResources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalFinance.Web.Resources.Transactions.TransactionsResources", typeof(TransactionsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All Transactions.
        /// </summary>
        public static string AllTransactions {
            get {
                return ResourceManager.GetString("AllTransactions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add new transaction.
        /// </summary>
        public static string AddTransactionCta {
            get {
                return ResourceManager.GetString("AddTransactionCta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add New Transaction.
        /// </summary>
        public static string AddTransactionTitle {
            get {
                return ResourceManager.GetString("AddTransactionTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add a new transaction to keep your records up to date..
        /// </summary>
        public static string AddTransactionSubtitle {
            get {
                return ResourceManager.GetString("AddTransactionSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Transaction.
        /// </summary>
        public static string AddTransactionButton {
            get {
                return ResourceManager.GetString("AddTransactionButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Participant.
        /// </summary>
        public static string Participant {
            get {
                return ResourceManager.GetString("Participant", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a participant.
        /// </summary>
        public static string ParticipantPlaceholder {
            get {
                return ResourceManager.GetString("ParticipantPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to + Add new participant.
        /// </summary>
        public static string AddParticipantCta {
            get {
                return ResourceManager.GetString("AddParticipantCta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        public static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a category.
        /// </summary>
        public static string CategoryPlaceholder {
            get {
                return ResourceManager.GetString("CategoryPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please fill in all required fields..
        /// </summary>
        public static string RequiredFieldsError {
            get {
                return ResourceManager.GetString("RequiredFieldsError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred. Please try again later..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add New Participant.
        /// </summary>
        public static string AddParticipantTitle {
            get {
                return ResourceManager.GetString("AddParticipantTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add a new recipient or sender to use in your transactions..
        /// </summary>
        public static string AddParticipantSubtitle {
            get {
                return ResourceManager.GetString("AddParticipantSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ParticipantNameLabel {
            get {
                return ResourceManager.GetString("ParticipantNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. Jane Doe.
        /// </summary>
        public static string ParticipantNamePlaceholder {
            get {
                return ResourceManager.GetString("ParticipantNamePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Photo URL (optional).
        /// </summary>
        public static string ParticipantImageLabel {
            get {
                return ResourceManager.GetString("ParticipantImageLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Participant.
        /// </summary>
        public static string AddParticipantButton {
            get {
                return ResourceManager.GetString("AddParticipantButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to + Add new category.
        /// </summary>
        public static string AddCategoryCta {
            get {
                return ResourceManager.GetString("AddCategoryCta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add New Category.
        /// </summary>
        public static string AddCategoryTitle {
            get {
                return ResourceManager.GetString("AddCategoryTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add a new category to organize your transactions..
        /// </summary>
        public static string AddCategorySubtitle {
            get {
                return ResourceManager.GetString("AddCategorySubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CategoryNameLabel {
            get {
                return ResourceManager.GetString("CategoryNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. Groceries.
        /// </summary>
        public static string CategoryNamePlaceholder {
            get {
                return ResourceManager.GetString("CategoryNamePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string AddCategoryButton {
            get {
                return ResourceManager.GetString("AddCategoryButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A to Z.
        /// </summary>
        public static string AToZ {
            get {
                return ResourceManager.GetString("AToZ", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Highest.
        /// </summary>
        public static string Highest {
            get {
                return ResourceManager.GetString("Highest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lowest.
        /// </summary>
        public static string Lowest {
            get {
                return ResourceManager.GetString("Lowest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Oldest.
        /// </summary>
        public static string Oldest {
            get {
                return ResourceManager.GetString("Oldest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        public static string Latest {
            get {
                return ResourceManager.GetString("Latest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Recipient / Sender.
        /// </summary>
        public static string RecipientSender {
            get {
                return ResourceManager.GetString("RecipientSender", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search transaction.
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Transaction Date.
        /// </summary>
        public static string TransactionDate {
            get {
                return ResourceManager.GetString("TransactionDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Z to A.
        /// </summary>
        public static string ZToA {
            get {
                return ResourceManager.GetString("ZToA", resourceCulture);
            }
        }
    }
}
