//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinance.Web.Resources.Transactions {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TransactionsResources_pt {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TransactionsResources_pt() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalFinance.Web.Resources.Transactions.TransactionsResources.pt", typeof(TransactionsResources_pt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Todas as Transações.
        /// </summary>
        public static string AllTransactions {
            get {
                return ResourceManager.GetString("AllTransactions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adicionar nova transação.
        /// </summary>
        public static string AddTransactionCta {
            get {
                return ResourceManager.GetString("AddTransactionCta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adicionar Nova Transação.
        /// </summary>
        public static string AddTransactionTitle {
            get {
                return ResourceManager.GetString("AddTransactionTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adicione uma nova transação para manter seus registros atualizados..
        /// </summary>
        public static string AddTransactionSubtitle {
            get {
                return ResourceManager.GetString("AddTransactionSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adicionar Transação.
        /// </summary>
        public static string AddTransactionButton {
            get {
                return ResourceManager.GetString("AddTransactionButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Participante.
        /// </summary>
        public static string Participant {
            get {
                return ResourceManager.GetString("Participant", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Selecione um participante.
        /// </summary>
        public static string ParticipantPlaceholder {
            get {
                return ResourceManager.GetString("ParticipantPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to + Adicionar novo participante.
        /// </summary>
        public static string AddParticipantCta {
            get {
                return ResourceManager.GetString("AddParticipantCta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Receita.
        /// </summary>
        public static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Despesa.
        /// </summary>
        public static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Selecione uma categoria.
        /// </summary>
        public static string CategoryPlaceholder {
            get {
                return ResourceManager.GetString("CategoryPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Por favor, preencha todos os campos obrigatórios..
        /// </summary>
        public static string RequiredFieldsError {
            get {
                return ResourceManager.GetString("RequiredFieldsError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro desconhecido. Tente novamente mais tarde..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adicionar Novo Participante.
        /// </summary>
        public static string AddParticipantTitle {
            get {
                return ResourceManager.GetString("AddParticipantTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adicione um novo destinatário ou remetente para usar em suas transações..
        /// </summary>
        public static string AddParticipantSubtitle {
            get {
                return ResourceManager.GetString("AddParticipantSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string ParticipantNameLabel {
            get {
                return ResourceManager.GetString("ParticipantNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ex. Maria Silva.
        /// </summary>
        public static string ParticipantNamePlaceholder {
            get {
                return ResourceManager.GetString("ParticipantNamePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to URL da Foto (opcional).
        /// </summary>
        public static string ParticipantImageLabel {
            get {
                return ResourceManager.GetString("ParticipantImageLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adicionar Participante.
        /// </summary>
        public static string AddParticipantButton {
            get {
                return ResourceManager.GetString("AddParticipantButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to + Adicionar nova categoria.
        /// </summary>
        public static string AddCategoryCta {
            get {
                return ResourceManager.GetString("AddCategoryCta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adicionar Nova Categoria.
        /// </summary>
        public static string AddCategoryTitle {
            get {
                return ResourceManager.GetString("AddCategoryTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adicione uma nova categoria para organizar suas transações..
        /// </summary>
        public static string AddCategorySubtitle {
            get {
                return ResourceManager.GetString("AddCategorySubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string CategoryNameLabel {
            get {
                return ResourceManager.GetString("CategoryNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ex. Mercado.
        /// </summary>
        public static string CategoryNamePlaceholder {
            get {
                return ResourceManager.GetString("CategoryNamePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adicionar Categoria.
        /// </summary>
        public static string AddCategoryButton {
            get {
                return ResourceManager.GetString("AddCategoryButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A a Z.
        /// </summary>
        public static string AToZ {
            get {
                return ResourceManager.GetString("AToZ", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maior valor.
        /// </summary>
        public static string Highest {
            get {
                return ResourceManager.GetString("Highest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Menor valor.
        /// </summary>
        public static string Lowest {
            get {
                return ResourceManager.GetString("Lowest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mais antigas.
        /// </summary>
        public static string Oldest {
            get {
                return ResourceManager.GetString("Oldest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mais recentes.
        /// </summary>
        public static string Latest {
            get {
                return ResourceManager.GetString("Latest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Destinatário / Remetente.
        /// </summary>
        public static string RecipientSender {
            get {
                return ResourceManager.GetString("RecipientSender", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Buscar transação.
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ordenar por.
        /// </summary>
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data da Transação.
        /// </summary>
        public static string TransactionDate {
            get {
                return ResourceManager.GetString("TransactionDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Z a A.
        /// </summary>
        public static string ZToA {
            get {
                return ResourceManager.GetString("ZToA", resourceCulture);
            }
        }
    }
}
